In [63]:
#@title Librerías a usar
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

print("Librerías cargadas")

Librerías cargadas


In [38]:
#@title Acceder al Drive

# Nota: la primera vez se debe confirmar el uso logueandose en "Google Drive File Stream" y obteniendo código de autentificación.
from google.colab import drive
drive.mount('/content/gdrive')

# directorio local en Google Drive
path = '/content/gdrive/My Drive/Entrega1/'  #@param {type:"string"}

#@title Cargar datos


#@markdown ### Archivo de datos a utilizar:
archivo_datos = 'grupo2_entrega2_data.csv'  #@param {type:"string"}
#@markdown ### Configuración del archivo CSV:
#@markdown ### Configuración del archivo CSV:
delimitador_columnas = '|' #@param {type:"string"}


# Carga los datos del CSV y muestra los primeros
dataset = pd.read_csv(path + archivo_datos,  sep=delimitador_columnas, engine="python")
print("Archivo de datos ", archivo_datos, " cargado")

ultimo_registro = dataset.iloc[-1]
dataset = dataset.iloc[0:-1]

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content
['.config', 'gdrive', 'sample_data']
Archivo de datos  grupo2_entrega2_data.csv  cargado


In [67]:
dataset

MES  Compras en supermercados en ARS  Compras en shopping en ARS  \
0   ene-17                        27.858872                    6.366881   
1   feb-17                        25.994200                    5.886707   
2   mar-17                        27.780007                    6.635468   
3   abr-17                        29.134272                    7.644786   
4   may-17                        27.969005                    7.244805   
..     ...                              ...                         ...   
72  ene-23                       316.578388                   78.536734   
73  feb-23                       318.416998                   81.817455   
74  mar-23                       363.148339                   92.678128   
75  abr-23                       385.814067                  114.148960   
76  may-23                       388.897176                  121.169065   

    Total nafta y gasoil en ARS   IPC  
0                     31.653561   102  
1                     28.496634   104  
2                     32.676969   106  
3                     29.263343   109  
4                     31.543718   111  
..                          ...   ...  
72                   320.416467  1203  
73                   304.200101  1283  
74                   371.381049  1381  
75                   360.388303  1497  
76                   387.346672  1614  

[77 rows x 5 columns]

In [66]:
ultimo_registro

MES                                    jun-23
Compras en supermercados en ARS    425.783283
Compras en shopping en ARS         144.743682
Total nafta y gasoil en ARS        397.851502
IPC                                      1710
Name: 77, dtype: object

In [50]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [51]:
X

array([[2.78588721e+01, 6.36688079e+00, 3.16535610e+01],
       [2.59942002e+01, 5.88670666e+00, 2.84966344e+01],
       [2.77800065e+01, 6.63546765e+00, 3.26769686e+01],
       [2.91342722e+01, 7.64478592e+00, 2.92633433e+01],
       [2.79690047e+01, 7.24480458e+00, 3.15437185e+01],
       [2.91327127e+01, 8.36161606e+00, 3.42987872e+01],
       [3.11823025e+01, 9.51474003e+00, 3.41900022e+01],
       [3.11548809e+01, 7.91820419e+00, 3.50321462e+01],
       [3.05215062e+01, 7.76750991e+00, 3.43341146e+01],
       [3.24459830e+01, 9.13701645e+00, 3.92205030e+01],
       [3.36289827e+01, 7.82932595e+00, 3.91180284e+01],
       [4.07663221e+01, 1.34038544e+01, 4.30393426e+01],
       [3.24792080e+01, 7.94076958e+00, 4.27772267e+01],
       [3.17368246e+01, 7.45826043e+00, 3.94225056e+01],
       [3.65312913e+01, 9.10506795e+00, 4.55112412e+01],
       [3.41137457e+01, 9.40416595e+00, 4.45292187e+01],
       [3.51331464e+01, 9.59719563e+00, 4.44397444e+01],
       [3.83382097e+01, 1.10980

In [52]:
y

array([ 102,  104,  106,  109,  111,  112,  114,  115,  118,  119,  121,
        125,  127,  130,  133,  137,  140,  145,  149,  155,  165,  174,
        180,  184,  190,  197,  206,  213,  220,  226,  230,  240,  254,
        262,  273,  283,  290,  296,  306,  310,  315,  322,  328,  337,
        347,  360,  371,  386,  402,  416,  436,  454,  469,  484,  498,
        510,  528,  547,  561,  582,  605,  633,  676,  717,  753,  793,
        852,  911,  967, 1029, 1079, 1135, 1203, 1283, 1381, 1497, 1614])

In [53]:

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

sc2 = StandardScaler()
y_train = sc2.fit_transform(y_train.reshape(-1,1))
y_test = sc2.transform(y_test.reshape(-1,1))

media_y = y.mean()
desvio_estandar_y = y.std()

In [54]:
X_test

array([[-9.40168358e-02, -3.41009112e-01, -8.87516282e-02],
       [ 2.64471045e+00,  2.29900311e+00,  2.61135799e+00],
       [ 7.94053484e-01,  9.51983197e-01,  6.18133208e-01],
       [ 1.91599247e-01, -2.05627963e-04,  4.35569300e-01],
       [-4.04556606e-01, -3.85560806e-01, -3.33138716e-01],
       [-5.78895261e-01, -4.98251145e-01, -5.32972272e-01],
       [ 1.29161753e+00,  1.02074461e+00,  1.46544124e+00],
       [-4.21270817e-01, -3.19035272e-01, -4.10212981e-01],
       [-1.84742493e-01, -6.05682318e-01, -3.46232977e-01],
       [ 1.63777965e+00,  1.75450718e+00,  1.63103172e+00],
       [-5.93813762e-01, -5.13832527e-01, -5.28241901e-01],
       [ 4.89688748e-01,  1.79809537e-01,  4.16663768e-01],
       [-8.05432233e-01, -6.38877209e-01, -9.38461154e-01],
       [-2.68240537e-01, -7.51675920e-01, -4.52462368e-01],
       [-2.75767759e-01, -7.38714287e-01, -3.57745205e-01],
       [-7.84560692e-01, -6.29430678e-01, -8.78603957e-01],
       [-6.43104962e-01, -5.76911130e-01

In [55]:
y_test

array([[-0.05297054],
       [ 2.56984669],
       [ 0.42926348],
       [ 0.20422094],
       [-0.39857158],
       [-0.5780698 ],
       [ 1.46070846],
       [-0.42804144],
       [-0.16549181],
       [ 1.62681128],
       [-0.55931626],
       [ 0.49088227],
       [-0.83794035],
       [-0.2512223 ],
       [-0.2271106 ],
       [-0.82186589],
       [-0.64772583],
       [-0.26729677],
       [ 0.03811811],
       [-0.31016201]])

In [56]:
red = tf.keras.models.Sequential()
red.add(tf.keras.layers.Dense(units=12, activation='relu'))
red.add(tf.keras.layers.Dense(units=6, activation='relu'))
red.add(tf.keras.layers.Dense(units=1, activation='linear'))
red.compile(optimizer = tf.keras.optimizers.SGD(learning_rate=0.3),
            loss = 'mse',
            metrics = ['mse', 'mae'])

# ENTRENAMOS
red.fit(X_train, y_train, batch_size = 32, epochs = 2000)

Epoch 1/2000
2/2 [==============================] - 0s 7ms/step - loss: 1.7327 - mse: 1.7327 - mae: 0.9291
Epoch 2/2000
2/2 [==============================] - 0s 7ms/step - loss: 1.1276 - mse: 1.1276 - mae: 0.8670
Epoch 3/2000
2/2 [==============================] - 0s 8ms/step - loss: 0.8390 - mse: 0.8390 - mae: 0.5340
Epoch 4/2000
2/2 [==============================] - 0s 7ms/step - loss: 0.4107 - mse: 0.4107 - mae: 0.4099
Epoch 5/2000
2/2 [==============================] - 0s 7ms/step - loss: 0.1444 - mse: 0.1444 - mae: 0.2918
Epoch 6/2000
2/2 [==============================] - 0s 9ms/step - loss: 0.1298 - mse: 0.1298 - mae: 0.2631
Epoch 7/2000
2/2 [==============================] - 0s 6ms/step - loss: 0.0260 - mse: 0.0260 - mae: 0.1231
Epoch 8/2000
2/2 [==============================] - 0s 7ms/step - loss: 0.0247 - mse: 0.0247 - mae: 0.1084
Epoch 9/2000
2/2 [==============================] - 0s 8ms/step - loss: 0.0521 - mse: 0.0521 - mae: 0.1373
Epoch 10/2000
2/2 [==================

In [57]:
predecido = red.predict(sc.transform([
    [425.783283, 144.743682, 397.851502 ]]
                         )
            )[0][0]

prediccion_ultimo_registro = predecido*desvio_estandar_y + media_y

1/1 [==============================] - 0s 86ms/step


In [58]:
prediccion_ultimo_registro

1747.0656648289928

In [61]:
y_pred = red.predict(X_test)

for i in range(len(y_pred)):
    error_absoluto = abs(y_test[i][0] - y_pred[i][0])
    error_relativo = abs(error_absoluto / y_test[i][0])*100

    line_info = f"ERROR RELATIVO % {error_relativo} || ERROR ABSOLUTO : {error_absoluto}"
    print(line_info)

1/1 [==============================] - 0s 22ms/step
ERROR RELATIVO % 163.26411036413813 || ERROR ABSOLUTO : 0.08648188019459738
ERROR RELATIVO % 39.87356972170109 || ERROR ABSOLUTO : 1.024689612475001
ERROR RELATIVO % 39.175787836231216 || ERROR ABSOLUTO : 0.16816734878994255
ERROR RELATIVO % 59.65195278450316 || ERROR ABSOLUTO : 0.12182177610057915
ERROR RELATIVO % 22.83993536406892 || ERROR ABSOLUTO : 0.09103349225440033
ERROR RELATIVO % 14.051520376017528 || ERROR ABSOLUTO : 0.08122759594044271
ERROR RELATIVO % 6.71682447394539 || ERROR ABSOLUTO : 0.09811322300870096
ERROR RELATIVO % 6.69186339870807 || ERROR ABSOLUTO : 0.028643948516585305
ERROR RELATIVO % 31.10633458853395 || ERROR ABSOLUTO : 0.05147843612934988
ERROR RELATIVO % 16.97593476346921 || ERROR ABSOLUTO : 0.27616642210869524
ERROR RELATIVO % 11.546603196570473 || ERROR ABSOLUTO : 0.06458202874012553
ERROR RELATIVO % 12.188469069164658 || ERROR ABSOLUTO : 0.05983103332555273
ERROR RELATIVO % 9.787219680903647 || ERROR AB

In [62]:
red.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_29 (Dense)            (None, 12)                48        
                                                                 
 dense_30 (Dense)            (None, 6)                 78        
                                                                 
 dense_31 (Dense)            (None, 1)                 7         
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
